

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice
spring.datasource.username=postgres
spring.datasource.password=Achal@85

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SUPER ADMIN (LOCAL)
# ===============================
superadmin.email=superadmin@local.com
superadmin.password=admin123


# ===============================
# STORAGE CONFIG
# ===============================

app.storage.type=local
app.storage.root=uploads

app.storage.company.logo=company/logo
app.storage.company.stamp=company/stamp
app.storage.company.sign=company/sign

app.storage.candidate=candidates
app.public-base-url=http://localhost:8080/uploads



