spring.application.name=invoice


spring.profiles.active=dev

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB



#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=achalyturkar@gmail.com
spring.mail.password=jyxk gwaw reuh gudq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

