spring.application.name=invoice


spring.profiles.active=dev

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

